<theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="platform:/plugin/com.ibm.designer.domino.stylekits/schema/stylekit.xsd">
	<resources>
		<metaData content="IE=edge" httpEquiv="X-UA-Compatible" />
		<metaData name="viewport" content="width=device-width, initial-scale=1" />
		<styleSheet href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" />
		<styleSheet href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" />
		<styleSheet href="/dashboard.css" />
		<script src="https://code.jquery.com/jquery-2.1.0.min.js" clientSide="true" />
		<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js" clientSide="true" />
	</resources>
</theme>